### ISSUE TITLE
Trouble running main and mainSOWFA

### ISSUE THREAD

**Issue by Xianlucky** [MarcusBecker-GitHub/FLORIDyn_Matlab#4]
Hello, Professor!
Today I discovered the FLORIDyn simulator and was excited to try out the possibilities.
First, I ran FLORIDyn_App and did not encounter any problems with the configuration.
When I run the main.m code, I notice that there is only one curve of power generated. This problem occurs when I run 2 or 3 turbines. And only two power curves appear when I run 4 turbines, as shown below:
![image](https://github.com/user-attachments/assets/fbbe89be-cad9-4fbc-879f-75d5504c1179)
![image](https://github.com/user-attachments/assets/16e57a6a-e9f4-464e-af04-6dc1f4a1f4a8)
When I change Control.Type = 'AxialInduction'; to Control.Type = 'FLORIDyn_greedy', this also occurs.
Then, there is also great interest in the presentation of your cover. I wonder how you achieved that? Is it implemented in FLORIDyn_App or main.m? Specifically as shown in the picture:
![image](https://github.com/user-attachments/assets/041269c4-23d4-4c17-96dc-32356b108d6e)

If possible, I would appreciate any help or advice anyone can give.

Thanks a lot!

**Comment by MarcusBecker-GitHub** [comment]
Hi @Xianlucky 
Nice to hear that you are interested in the code!
It's been a while since I ran this version of FLORIDyn, I plan to release the new version soon.

About your issues, du you mind sharing the main.m that you ran? Just so I can try to recreate the issue.

About the Figure, I customised the code to just create OPs slightly above and below hub height and ran the simulation while saving snapshots every time step. Eventually I was able to create the animation.
You should be able to create a similar result if you set the distribution method to '2D_horizontal' which is passed to [assembleOPList](https://github.com/MarcusBecker-GitHub/FLORIDyn_Matlab/blob/main/ObservationPoints/assembleOPList.m)

Best regards

**Comment by Xianlucky** [comment]
Hello, Professer!
I am very glad to get your reply!
Regarding your mention of only creating OPs slightly above and slightly below hub height, and saving a snapshot of each time step while running the simulation, ultimately, creating the animation. Can your code keep a snapshot of each time step during the simulation? What concrete steps can I take to be like you, to achieve what you say?
My questions are mainly as follows:
First, when I run the main.m code I only change the code shown in the figure, only two power curves appear. When I changed loadLayout("threeDTU10MW") to loadLayout("nineDTU10MW"), only three power curves appeared, as shown below:
![image](https://github.com/user-attachments/assets/104221da-5011-46b7-9660-77e53f1c00b2)
![image](https://github.com/user-attachments/assets/dd2096f0-3d72-42c6-b672-788de97d5faa)
Second, when I run the FLORIDyn_App.mlapp, I also have an incomplete power curve display. When I made the change to fourDTU10MW and nineDTU10MW, I knew that the app was associated with main.m. The specific figure is shown as follows:
![image](https://github.com/user-attachments/assets/84912776-bd3f-4336-894f-3bb36b2ccc2e)
![image](https://github.com/user-attachments/assets/216fa92e-c554-4ead-bad4-64ea0354c4f5)
Third, I am very curious about your paper (Becker, Marcus, et al. "The revised FLORIDyn model: , Implementation of heterogeneous flow and the Gaussian wake." Wind Energy Science Discussions 2022 (2022): 1-25.), some of the pictures are very beautiful. At the same time, I am also very interested in your FLORIDyn_Matlab-main code, how to implement the wind deflection at a certain time? For example, deflection occurs at t=200s and t=800s, as shown in the figure below:
![image](https://github.com/user-attachments/assets/c9eec4cf-b26e-4242-b8f0-7cb1a2d9c7d6)
Finally, it is about how to implement unfiltered and filtered FLORIDyn data. Will your FLORIDyn_Matlab-main code be implemented?
![image](https://github.com/user-attachments/assets/6db67085-fb6d-4731-b0a3-4d3eaabc84fb)
Since the software I use is Fluent and the model I use is ADM, can the generated data also be implemented on your code? This is my biggest doubt!
Since the software I use is Fluent and the model I use is ADM, can the generated data also be implemented on your code? This is my biggest doubt!
![image](https://github.com/user-attachments/assets/753b2976-721f-43c7-bb80-a152512686b3)
If you use your code to research and publish a paper, is there some infringement?
I am also very interested in your team's implementation of OFF.That OFF code, I feel the power production is better! Is your team working on further development?
Thank you very much for answering my questions!
Thanks a lot!

**Comment by MarcusBecker-GitHub** [comment]
# Issue 1 - fewer turbines appearing than expected
![Bildschirmfoto 2024-09-02 um 09 53 53](https://github.com/user-attachments/assets/672606c2-b31e-42f6-a23d-2243e285792a)
My suspicion is that the lines are on top of each other, since all turbines are either waked in the exact same manner, or are in free stream conditions. You could verify this by waking one turbine front row turbine and not the other.

Let me know if this worked!

# Questions regarding the publication
## How to implement wind direction changes
The main.m calls a function [loadWindField](https://github.com/MarcusBecker-GitHub/FLORIDyn_Matlab/blob/main/WindField/loadWindField.m) where you can pass the expected environmental behaviour.  Currently there are only a small selection, so you'll need to extend it if you want something else. You can try '+60DegChange' for instance to get the wind direction change from the paper.

## Filtering
If I recall correctly the filtering was done as a post processing and is not part of the code published here. Have a look at [the zero phase filtering](https://nl.mathworks.com/help/signal/ref/filtfilt.html) of Matlab, then you can recreate the plots.
Generally I put a lot of work into improving the figures for the publication, the code unfortunately does not provide them in this way directly.

## Usage of a different CFD solver to compare to
Have a look at the SOWFA files in /VerificationDtaa/csv/ 
If your code can produce .csv files like this, you can read them in. They just need to be named adequately: you'll need ++++nacelleYaw.csv, ++++generatorPower.csv, where (++++) is the file2val variable that you set in SOWFA_main.m

# Usage of the Code
The code is published under the [GPL-3.0 license](https://github.com/MarcusBecker-GitHub/FLORIDyn_Matlab/issues/4#GPL-3.0-1-ov-file), so you can use it, but you must adhere to the license rules. You can find summaries of the license. If you publish work based on the code, please refer to the [paper](https://wes.copernicus.org/articles/7/2163/2022/).

# OFF code
We are indeed further working on OFF, but other aspects have higher priorities right now, so it's a bit slow. Mainly we are working on the verification of the code and control applications. Great to hear that you are interested in it!

**Comment by Xianlucky** [comment]
**Questions about curves**

Your answer is correct because the curves overlap and only part of the power curve is shown. I solved your curve overlap problem by changing the yaw conditions. At the same time, I changed the wind direction by changing the loadWindField, and the corresponding data was also obtained. It's a really useful tool.Thank you very much for your clarification.
![image](https://github.com/user-attachments/assets/37f4b8de-ec47-4c02-ac37-c1deb4749236)

I still have some questions. First, as for the deflection at t=200s and t=800s in your paper, it is not specifically expressed in your code, do I need to add cases related to loadWindField to realize it? Second, regarding what you mentioned about creating OP only slightly above and slightly below the hub height, and saving a snapshot of each time step while running the simulation, and finally creating the animation. That is also a very interesting process, so I want to implement it. Would this be possible simply by setting the distribution method passed to the assembleOPList to "2D_horizontal"? Those snapshots should be preserved in your code, right? Finally, thank you very much for your help, and I will continue to learn more about the code here. I've also learned a bit about OFF, and the research your team has done is very meaningful.

Thanks a lot!

**Comment by MarcusBecker-GitHub** [comment]
With this comment I will close this issue, as there doesn't seem to be a bug in the code.

## Yaw angle changes
The yaw angle changes are applied by reading in a time series. The time series for the 3 turbine case is given in [this csv](https://github.com/MarcusBecker-GitHub/FLORIDyn_Matlab/blob/main/ValidationData/csv/3T_neg_y_nacelleYaw.csv)
To load and run this time series you need to set `Control.Type = 'SOWFA_greedy_yaw';` and `file2val = '/ValidationData/csv/3T_neg_y_';` to eventually load 3T_neg_y_nacelleYaw.csv and 3T_neg_y_powerGenerated.csv
The data is stored in Control.yawSOWFA and is applied in the [Controller script](https://github.com/MarcusBecker-GitHub/FLORIDyn_Matlab/blob/main/Controller/ControllerScript.m).

## Plotting
To get online plotting set
`Vis.online      = true;`
to save the snapshots (Requires a folder "Snapshot" in the main directory), set 
`Vis.Snapshots   = true;`
To get a flow field visualisation *after* the simulation, enable this 
`Vis.FlowField   = true;`

You'll then need to use another program to create a movie from the stored snapshots.
Have a look at the code at the end of [OnlineVis_plot](https://github.com/MarcusBecker-GitHub/FLORIDyn_Matlab/blob/main/Visulization/OnlineVis_plot.m) to understand how the data is stored.

The `2D_horizontal` option is NOT recommended to derive any meaningful numbers from the power generated, it is purely there for visualisation purposes. To achieve the *very* same plot, you might need to modify the code in [OnlineVis_plot](https://github.com/MarcusBecker-GitHub/FLORIDyn_Matlab/blob/main/Visulization/OnlineVis_plot.m), but carefully reading it should allow you to do so.

Best of luck with your research!
